package com.issiaa2016.semanticmodelimpl;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Thu Oct 27 23:14:59 BST 2016 by dmrgo
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Cell
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CELL.<p>
     * 
     */
    public static final OWLClass CLASS_CELL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Cell"));

    /* ***************************************************
     * Class http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ComplexSkill
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPLEXSKILL.<p>
     * 
     */
    public static final OWLClass CLASS_COMPLEXSKILL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ComplexSkill"));

    /* ***************************************************
     * Class http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Disturbance
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISTURBANCE.<p>
     * 
     */
    public static final OWLClass CLASS_DISTURBANCE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Disturbance"));

    /* ***************************************************
     * Class http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Parameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_PARAMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Parameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Product
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRODUCT.<p>
     * 
     */
    public static final OWLClass CLASS_PRODUCT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Product"));

    /* ***************************************************
     * Class http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Resource
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESOURCE.<p>
     * 
     */
    public static final OWLClass CLASS_RESOURCE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Resource"));

    /* ***************************************************
     * Class http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#SimpleSkill
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SIMPLESKILL.<p>
     * 
     */
    public static final OWLClass CLASS_SIMPLESKILL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#SimpleSkill"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Consumes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONSUMES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONSUMES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Consumes"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Contains
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Contains"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ExecutesComplex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXECUTESCOMPLEX.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXECUTESCOMPLEX = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ExecutesComplex"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ExecutesSimple
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXECUTESSIMPLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXECUTESSIMPLE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ExecutesSimple"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Produces
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PRODUCES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PRODUCES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Produces"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#complete
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COMPLETE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COMPLETE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#complete"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#consistsOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONSISTSOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONSISTSOF = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#consistsOf"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#have
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAVE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAVE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#have"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#incorporate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INCORPORATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INCORPORATE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#incorporate"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#perform
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PERFORM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PERFORM = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#perform"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ComplexSkills
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property COMPLEXSKILLS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_COMPLEXSKILLS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ComplexSkills"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Description
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DESCRIPTION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Description"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Disturbance
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DISTURBANCE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DISTURBANCE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Disturbance"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Friendly_Name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FRIENDLY_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FRIENDLY_NAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Friendly_Name"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ID"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Manufacturer
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MANUFACTURER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MANUFACTURER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Manufacturer"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Parameters
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PARAMETERS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PARAMETERS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Parameters"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Resource
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property RESOURCE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_RESOURCE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Resource"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#SimpleSkills
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SIMPLESKILLS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SIMPLESKILLS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#SimpleSkills"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Type
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TYPE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Type"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Value
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VALUE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Value"));


}
