/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ConsoleAgent;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.HashMap;
import javax.swing.JComboBox;

/**
 *
 * @author André Dionisio Rocha
 */
public class ConsoleFrame extends javax.swing.JFrame {

    /**
     * Creates new form ConsoleFrame
     */
    private final frameToAgentCom myFrameToAgentComm;
    private boolean firstTimeOP = true, firstTimeSH = true, firstTimeTH = true;
    private String OPs = new String(), Hw = new String(), SHs = new String(), THs = new String();
    private String opLocationsChoosen, thChoosen;
    private HashMap<String, Boolean> task2Combo = new HashMap<>();

    ConsoleFrame(frameToAgentCom myFrameToAgentComm) {
        initComponents();

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double width = screenSize.getWidth();
        double height = screenSize.getHeight();
        this.setLocation((int) (width / 4), (int) (height / 2));

        this.myFrameToAgentComm = myFrameToAgentComm;

        this.jButtonProduct.setEnabled(false);
        this.jTextFieldProductID.setEnabled(false);
        this.jTextFieldProductName.setEnabled(false);
        this.jTextFieldProductTasks.setEnabled(false);

        this.jButtonTask.setEnabled(false);
        this.jTextFieldTaskID.setEnabled(false);
        this.jTextFieldTaskName.setEnabled(false);
        this.jComboBoxTaskHardware.setEnabled(false);
        this.jTextFieldTaskSupervisors.setEnabled(false);
        this.SubTasksTextField.setEnabled(false);

        this.jButtonSupervisor.setEnabled(false);
        this.jTextFieldSupervisorId.setEnabled(false);
        this.jTextFieldSupervisorName.setEnabled(false);
        this.jTextFieldSupervisorOperationals.setEnabled(false);

        this.jComboBoxOperationalLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"D_4", "D_5", "D_7", "D_8", "D_9"}));
        this.jComboBoxOperationalLocation.setSelectedIndex(0);

        this.jComboBoxTaskHardware.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel4 = new javax.swing.JLabel();
        jButtonLayout1 = new javax.swing.JButton();
        jButtonLayout2 = new javax.swing.JButton();
        jTextFieldProductTasks = new javax.swing.JTextField();
        jButtonProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldOperational_ID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonResource = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldProductID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldProductName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldSupervisorId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldSupervisorName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldSupervisorOperationals = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButtonSupervisor = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldOperationalName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldOperationalHardwareType = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldTaskID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldTaskName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldTaskSupervisors = new javax.swing.JTextField();
        jButtonTask = new javax.swing.JButton();
        SubTasksLabel = new javax.swing.JLabel();
        SubTasksTextField = new javax.swing.JTextField();
        OperationalPriorityLabel = new javax.swing.JLabel();
        OperationalPriorityTextField = new javax.swing.JTextField();
        jComboBoxOperationalLocation = new javax.swing.JComboBox<>();
        jComboBoxTaskHardware = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulation Console");
        setAlwaysOnTop(true);

        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SRCIM - Simulation Tool");

        jButtonLayout1.setText("Launch Layout 1");
        jButtonLayout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayout1ActionPerformed(evt);
            }
        });

        jButtonLayout2.setText("Launch Layout 2");
        jButtonLayout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLayout2ActionPerformed(evt);
            }
        });

        jTextFieldProductTasks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductTasksActionPerformed(evt);
            }
        });

        jButtonProduct.setText("Launch New Product");
        jButtonProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductProductActionPerformed(evt);
            }
        });

        jLabel1.setText("Launch Products");

        jLabel2.setText("Product Tasks (Separated by ; - Ex:Tk A;Tk B;)");

        jLabel3.setText("Launch Operational");

        jTextFieldOperational_ID.setText("Operational_1");
        jTextFieldOperational_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOperational_IDActionPerformed(evt);
            }
        });

        jLabel6.setText("Operational ID (Ex:Operational_1)");

        jLabel7.setText("Operational Location");

        jButtonResource.setText("Launch New Operational");
        jButtonResource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperationalActionPerformed(evt);
            }
        });

        jLabel8.setText("Product ID (Ex: Product_1)");

        jTextFieldProductID.setText("Product_1");
        jTextFieldProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductIDActionPerformed(evt);
            }
        });

        jLabel9.setText("Product Name (Ex: Product 1)");

        jTextFieldProductName.setText("Product 1");
        jTextFieldProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProductNameActionPerformed(evt);
            }
        });

        jLabel10.setText("Launch Supervisor");

        jLabel11.setText("Supervisor ID (Ex: Supervisor_1)");

        jTextFieldSupervisorId.setText("Supervisor_1");
        jTextFieldSupervisorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSupervisorIdActionPerformed(evt);
            }
        });

        jLabel12.setText("Supervisor Name (Ex: Supervisor 1)");

        jTextFieldSupervisorName.setText("Supervisor 1");
        jTextFieldSupervisorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSupervisorNameActionPerformed(evt);
            }
        });

        jLabel13.setText("Supervisor Operationals (Ex: Operational 1; Operational 2;)");

        jTextFieldSupervisorOperationals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSupervisorOperationalsActionPerformed(evt);
            }
        });

        jLabel14.setText("Launch Task");

        jButtonSupervisor.setText("Launch New Supervisor");
        jButtonSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupervisorActionPerformed(evt);
            }
        });

        jLabel15.setText("Operational Name (Ex: Operational 1)");

        jTextFieldOperationalName.setText("Operational 1");
        jTextFieldOperationalName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOperationalNameActionPerformed(evt);
            }
        });

        jLabel16.setText("Operational HardwareType (Ex:station_A;gripper_A;)");

        jTextFieldOperationalHardwareType.setText("station_A");

        jLabel17.setText("Task ID (Ex: Tk_A)");

        jTextFieldTaskID.setText("Tk_A");
        jTextFieldTaskID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTaskIDActionPerformed(evt);
            }
        });

        jLabel18.setText("Task Name (Ex: Tk A)");

        jTextFieldTaskName.setText("Tk A");

        jLabel19.setText("Task HardwareNeeded");

        jLabel20.setText("Task Supervisors (Ex: Supervisor 1;Supervisor 2;)");

        jTextFieldTaskSupervisors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTaskSupervisorsActionPerformed(evt);
            }
        });

        jButtonTask.setText("Launch New Task");
        jButtonTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaskActionPerformed(evt);
            }
        });

        SubTasksLabel.setText("SubTasks (Ex: Tk A;Tk B;)");

        OperationalPriorityLabel.setText("Operational Priority (The Higher The Better)");

        OperationalPriorityTextField.setText("1");
        OperationalPriorityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperationalPriorityTextFieldActionPerformed(evt);
            }
        });

        jComboBoxOperationalLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxOperationalLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOperationalLocationActionPerformed(evt);
            }
        });

        jComboBoxTaskHardware.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTaskHardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTaskHardwareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTask, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 64, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonLayout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLayout2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(OperationalPriorityLabel))
                                .addGap(0, 61, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SubTasksLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxTaskHardware, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldTaskSupervisors, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTaskID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTaskName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SubTasksTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldProductTasks, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldProductName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldProductID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(OperationalPriorityTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonResource, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldOperational_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                                    .addComponent(jTextFieldOperationalHardwareType, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldOperationalName, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxOperationalLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(55, 55, 55)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldSupervisorName)
                                    .addComponent(jTextFieldSupervisorOperationals, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                                .addComponent(jTextFieldSupervisorId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLayout1)
                    .addComponent(jButtonLayout2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOperational_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSupervisorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSupervisorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOperationalName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOperationalHardwareType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSupervisorOperationals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSupervisor)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxOperationalLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OperationalPriorityLabel)
                .addGap(0, 0, 0)
                .addComponent(OperationalPriorityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonResource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTaskID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTaskName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProductTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTaskHardware, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTaskSupervisors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubTasksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubTasksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButtonTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLayout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayout1ActionPerformed
        this.choseLayout("Layout1Rules", "HardwareSimulationLayout1");
    }//GEN-LAST:event_jButtonLayout1ActionPerformed

    private void jButtonLayout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLayout2ActionPerformed
        this.choseLayout("Layout2Rules", "HardwareSimulationLayout2");
    }//GEN-LAST:event_jButtonLayout2ActionPerformed

    private void jButtonProductProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductProductActionPerformed
        this.myFrameToAgentComm.launchNewProduct(this.jTextFieldProductID.getText(), this.jTextFieldProductName.getText(), this.jTextFieldProductTasks.getText());
    }//GEN-LAST:event_jButtonProductProductActionPerformed

    private void jButtonOperationalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperationalActionPerformed
        this.myFrameToAgentComm.launchNewOperational(this.jTextFieldOperational_ID.getText(), this.jTextFieldOperationalName.getText(), this.jTextFieldOperationalHardwareType.getText(), this.opLocationsChoosen, this.OperationalPriorityTextField.getText());
        this.jButtonSupervisor.setEnabled(true);
        this.jTextFieldSupervisorId.setEnabled(true);
        this.jTextFieldSupervisorName.setEnabled(true);
        this.jTextFieldSupervisorOperationals.setEnabled(true);

        if (this.firstTimeOP) {
            this.OPs = this.jTextFieldOperationalName.getText() + ";";
            this.firstTimeOP = false;
        } else {
            this.OPs = this.OPs + this.jTextFieldOperationalName.getText() + ";";
        }

        this.jTextFieldSupervisorOperationals.setText(this.OPs);

        if (this.task2Combo.get(this.jTextFieldOperationalHardwareType.getText()) == null) {
            this.jComboBoxTaskHardware.addItem(this.jTextFieldOperationalHardwareType.getText());
            this.task2Combo.put(this.jTextFieldOperationalHardwareType.getText(), true);
        }
    }//GEN-LAST:event_jButtonOperationalActionPerformed

    private void jTextFieldProductTasksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductTasksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductTasksActionPerformed

    private void jTextFieldOperational_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOperational_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOperational_IDActionPerformed

    private void jTextFieldProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductIDActionPerformed

    private void jTextFieldProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProductNameActionPerformed

    private void jTextFieldSupervisorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSupervisorIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupervisorIdActionPerformed

    private void jButtonSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupervisorActionPerformed
        this.myFrameToAgentComm.launchNewSupervisor(this.jTextFieldSupervisorId.getText(), this.jTextFieldSupervisorName.getText(), this.jTextFieldSupervisorOperationals.getText());
        this.jButtonTask.setEnabled(true);
        this.jTextFieldTaskID.setEnabled(true);
        this.jTextFieldTaskName.setEnabled(true);
        this.jComboBoxTaskHardware.setEnabled(true);
        this.jTextFieldTaskSupervisors.setEnabled(true);
        this.SubTasksTextField.setEnabled(true);

        if (this.firstTimeSH) {
            this.SHs = this.jTextFieldSupervisorName.getText() + ";";
            this.firstTimeSH = false;
        } else {
            this.SHs = this.SHs + this.jTextFieldSupervisorName.getText() + ";";
        }
        this.jTextFieldTaskSupervisors.setText(this.SHs);
    }//GEN-LAST:event_jButtonSupervisorActionPerformed

    private void jTextFieldOperationalNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOperationalNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOperationalNameActionPerformed

    private void jTextFieldTaskIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTaskIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTaskIDActionPerformed

    private void jButtonTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaskActionPerformed
        this.myFrameToAgentComm.launchNewTask(this.jTextFieldTaskID.getText(), this.jTextFieldTaskName.getText(), this.thChoosen, this.jTextFieldTaskSupervisors.getText(), this.SubTasksTextField.getText());
        this.jButtonProduct.setEnabled(true);
        this.jTextFieldProductID.setEnabled(true);
        this.jTextFieldProductName.setEnabled(true);
        this.jTextFieldProductTasks.setEnabled(true);

        if (this.firstTimeTH) {
            this.THs = this.jTextFieldTaskName.getText() + ";";
            this.firstTimeTH = false;
        } else {
            this.THs = this.THs + this.jTextFieldTaskName.getText() + ";";
        }
        this.jTextFieldProductTasks.setText(this.THs);
    }//GEN-LAST:event_jButtonTaskActionPerformed

    private void jTextFieldSupervisorOperationalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSupervisorOperationalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupervisorOperationalsActionPerformed

    private void jTextFieldTaskSupervisorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTaskSupervisorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTaskSupervisorsActionPerformed

    private void jTextFieldSupervisorNameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldTaskHardwareNeededActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTaskHardwareNeededActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTaskHardwareNeededActionPerformed

    private void OperationalPriorityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperationalPriorityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OperationalPriorityTextFieldActionPerformed

    private void jComboBoxOperationalLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOperationalLocationActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jComboBoxOperationalLocation) {
            JComboBox cb = (JComboBox) evt.getSource();
            String msg = (String) cb.getSelectedItem();

            opLocationsChoosen = msg;
        }
    }//GEN-LAST:event_jComboBoxOperationalLocationActionPerformed

    private void jComboBoxTaskHardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTaskHardwareActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jComboBoxTaskHardware) {
            JComboBox cb = (JComboBox) evt.getSource();
            String msg = (String) cb.getSelectedItem();

            thChoosen = msg;
        }
    }//GEN-LAST:event_jComboBoxTaskHardwareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsoleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OperationalPriorityLabel;
    private javax.swing.JTextField OperationalPriorityTextField;
    private javax.swing.JLabel SubTasksLabel;
    private javax.swing.JTextField SubTasksTextField;
    private javax.swing.JButton jButtonLayout1;
    private javax.swing.JButton jButtonLayout2;
    private javax.swing.JButton jButtonProduct;
    private javax.swing.JButton jButtonResource;
    private javax.swing.JButton jButtonSupervisor;
    private javax.swing.JButton jButtonTask;
    private javax.swing.JComboBox<String> jComboBoxOperationalLocation;
    private javax.swing.JComboBox<String> jComboBoxTaskHardware;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldOperationalHardwareType;
    private javax.swing.JTextField jTextFieldOperationalName;
    private javax.swing.JTextField jTextFieldOperational_ID;
    private javax.swing.JTextField jTextFieldProductID;
    private javax.swing.JTextField jTextFieldProductName;
    private javax.swing.JTextField jTextFieldProductTasks;
    private javax.swing.JTextField jTextFieldSupervisorId;
    private javax.swing.JTextField jTextFieldSupervisorName;
    private javax.swing.JTextField jTextFieldSupervisorOperationals;
    private javax.swing.JTextField jTextFieldTaskID;
    private javax.swing.JTextField jTextFieldTaskName;
    private javax.swing.JTextField jTextFieldTaskSupervisors;
    // End of variables declaration//GEN-END:variables

    private void choseLayout(String rulesLib, String hwLib) {
        this.myFrameToAgentComm.launchNewSimulationEnvironment(rulesLib, hwLib);
        this.jButtonLayout1.setEnabled(false);
        this.jButtonLayout2.setEnabled(false);
    }
}
