package 3oTrabProtege;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: ComplexTaskHolon <br>
 * @version generated on Wed Dec 28 18:45:57 GMT 2016 by dmrg
 */

public interface ComplexTaskHolon extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#AsksSimple
     */
     
    /**
     * Gets all property values for the AsksSimple property.<p>
     * 
     * @returns a collection of values for the AsksSimple property.
     */
    Collection<? extends SimpleTaskHolon> getAsksSimple();

    /**
     * Checks if the class has a AsksSimple property value.<p>
     * 
     * @return true if there is a AsksSimple property value.
     */
    boolean hasAsksSimple();

    /**
     * Adds a AsksSimple property value.<p>
     * 
     * @param newAsksSimple the AsksSimple property value to be added
     */
    void addAsksSimple(SimpleTaskHolon newAsksSimple);

    /**
     * Removes a AsksSimple property value.<p>
     * 
     * @param oldAsksSimple the AsksSimple property value to be removed.
     */
    void removeAsksSimple(SimpleTaskHolon oldAsksSimple);


    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#CTHAnswerPH
     */
     
    /**
     * Gets all property values for the CTHAnswerPH property.<p>
     * 
     * @returns a collection of values for the CTHAnswerPH property.
     */
    Collection<? extends ProductHolon> getCTHAnswerPH();

    /**
     * Checks if the class has a CTHAnswerPH property value.<p>
     * 
     * @return true if there is a CTHAnswerPH property value.
     */
    boolean hasCTHAnswerPH();

    /**
     * Adds a CTHAnswerPH property value.<p>
     * 
     * @param newCTHAnswerPH the CTHAnswerPH property value to be added
     */
    void addCTHAnswerPH(ProductHolon newCTHAnswerPH);

    /**
     * Removes a CTHAnswerPH property value.<p>
     * 
     * @param oldCTHAnswerPH the CTHAnswerPH property value to be removed.
     */
    void removeCTHAnswerPH(ProductHolon oldCTHAnswerPH);


    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ID
     */
     
    /**
     * Gets all property values for the ID property.<p>
     * 
     * @returns a collection of values for the ID property.
     */
    Collection<? extends String> getID();

    /**
     * Checks if the class has a ID property value.<p>
     * 
     * @return true if there is a ID property value.
     */
    boolean hasID();

    /**
     * Adds a ID property value.<p>
     * 
     * @param newID the ID property value to be added
     */
    void addID(String newID);

    /**
     * Removes a ID property value.<p>
     * 
     * @param oldID the ID property value to be removed.
     */
    void removeID(String oldID);



    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Name
     */
     
    /**
     * Gets all property values for the Name property.<p>
     * 
     * @returns a collection of values for the Name property.
     */
    Collection<? extends String> getName();

    /**
     * Checks if the class has a Name property value.<p>
     * 
     * @return true if there is a Name property value.
     */
    boolean hasName();

    /**
     * Adds a Name property value.<p>
     * 
     * @param newName the Name property value to be added
     */
    void addName(String newName);

    /**
     * Removes a Name property value.<p>
     * 
     * @param oldName the Name property value to be removed.
     */
    void removeName(String oldName);



    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#SubTasks
     */
     
    /**
     * Gets all property values for the SubTasks property.<p>
     * 
     * @returns a collection of values for the SubTasks property.
     */
    Collection<? extends String> getSubTasks();

    /**
     * Checks if the class has a SubTasks property value.<p>
     * 
     * @return true if there is a SubTasks property value.
     */
    boolean hasSubTasks();

    /**
     * Adds a SubTasks property value.<p>
     * 
     * @param newSubTasks the SubTasks property value to be added
     */
    void addSubTasks(String newSubTasks);

    /**
     * Removes a SubTasks property value.<p>
     * 
     * @param oldSubTasks the SubTasks property value to be removed.
     */
    void removeSubTasks(String oldSubTasks);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
