package 3oTrabProtege;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: OperationalHolon <br>
 * @version generated on Wed Dec 28 18:45:57 GMT 2016 by dmrg
 */

public interface OperationalHolon extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Answer
     */
     
    /**
     * Gets all property values for the Answer property.<p>
     * 
     * @returns a collection of values for the Answer property.
     */
    Collection<? extends SupervisorHolon> getAnswer();

    /**
     * Checks if the class has a Answer property value.<p>
     * 
     * @return true if there is a Answer property value.
     */
    boolean hasAnswer();

    /**
     * Adds a Answer property value.<p>
     * 
     * @param newAnswer the Answer property value to be added
     */
    void addAnswer(SupervisorHolon newAnswer);

    /**
     * Removes a Answer property value.<p>
     * 
     * @param oldAnswer the Answer property value to be removed.
     */
    void removeAnswer(SupervisorHolon oldAnswer);


    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#HardwareType
     */
     
    /**
     * Gets all property values for the HardwareType property.<p>
     * 
     * @returns a collection of values for the HardwareType property.
     */
    Collection<? extends String> getHardwareType();

    /**
     * Checks if the class has a HardwareType property value.<p>
     * 
     * @return true if there is a HardwareType property value.
     */
    boolean hasHardwareType();

    /**
     * Adds a HardwareType property value.<p>
     * 
     * @param newHardwareType the HardwareType property value to be added
     */
    void addHardwareType(String newHardwareType);

    /**
     * Removes a HardwareType property value.<p>
     * 
     * @param oldHardwareType the HardwareType property value to be removed.
     */
    void removeHardwareType(String oldHardwareType);



    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ID
     */
     
    /**
     * Gets all property values for the ID property.<p>
     * 
     * @returns a collection of values for the ID property.
     */
    Collection<? extends String> getID();

    /**
     * Checks if the class has a ID property value.<p>
     * 
     * @return true if there is a ID property value.
     */
    boolean hasID();

    /**
     * Adds a ID property value.<p>
     * 
     * @param newID the ID property value to be added
     */
    void addID(String newID);

    /**
     * Removes a ID property value.<p>
     * 
     * @param oldID the ID property value to be removed.
     */
    void removeID(String oldID);



    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Location
     */
     
    /**
     * Gets all property values for the Location property.<p>
     * 
     * @returns a collection of values for the Location property.
     */
    Collection<? extends String> getLocation();

    /**
     * Checks if the class has a Location property value.<p>
     * 
     * @return true if there is a Location property value.
     */
    boolean hasLocation();

    /**
     * Adds a Location property value.<p>
     * 
     * @param newLocation the Location property value to be added
     */
    void addLocation(String newLocation);

    /**
     * Removes a Location property value.<p>
     * 
     * @param oldLocation the Location property value to be removed.
     */
    void removeLocation(String oldLocation);



    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Name
     */
     
    /**
     * Gets all property values for the Name property.<p>
     * 
     * @returns a collection of values for the Name property.
     */
    Collection<? extends String> getName();

    /**
     * Checks if the class has a Name property value.<p>
     * 
     * @return true if there is a Name property value.
     */
    boolean hasName();

    /**
     * Adds a Name property value.<p>
     * 
     * @param newName the Name property value to be added
     */
    void addName(String newName);

    /**
     * Removes a Name property value.<p>
     * 
     * @param oldName the Name property value to be removed.
     */
    void removeName(String oldName);



    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Priority
     */
     
    /**
     * Gets all property values for the Priority property.<p>
     * 
     * @returns a collection of values for the Priority property.
     */
    Collection<? extends Integer> getPriority();

    /**
     * Checks if the class has a Priority property value.<p>
     * 
     * @return true if there is a Priority property value.
     */
    boolean hasPriority();

    /**
     * Adds a Priority property value.<p>
     * 
     * @param newPriority the Priority property value to be added
     */
    void addPriority(Integer newPriority);

    /**
     * Removes a Priority property value.<p>
     * 
     * @param oldPriority the Priority property value to be removed.
     */
    void removePriority(Integer oldPriority);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
