package 3oTrabProtege;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: SimpleTaskHolon <br>
 * @version generated on Wed Dec 28 18:45:57 GMT 2016 by dmrg
 */

public interface SimpleTaskHolon extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#AnswerCTH
     */
     
    /**
     * Gets all property values for the AnswerCTH property.<p>
     * 
     * @returns a collection of values for the AnswerCTH property.
     */
    Collection<? extends ComplexTaskHolon> getAnswerCTH();

    /**
     * Checks if the class has a AnswerCTH property value.<p>
     * 
     * @return true if there is a AnswerCTH property value.
     */
    boolean hasAnswerCTH();

    /**
     * Adds a AnswerCTH property value.<p>
     * 
     * @param newAnswerCTH the AnswerCTH property value to be added
     */
    void addAnswerCTH(ComplexTaskHolon newAnswerCTH);

    /**
     * Removes a AnswerCTH property value.<p>
     * 
     * @param oldAnswerCTH the AnswerCTH property value to be removed.
     */
    void removeAnswerCTH(ComplexTaskHolon oldAnswerCTH);


    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Asks
     */
     
    /**
     * Gets all property values for the Asks property.<p>
     * 
     * @returns a collection of values for the Asks property.
     */
    Collection<? extends SupervisorHolon> getAsks();

    /**
     * Checks if the class has a Asks property value.<p>
     * 
     * @return true if there is a Asks property value.
     */
    boolean hasAsks();

    /**
     * Adds a Asks property value.<p>
     * 
     * @param newAsks the Asks property value to be added
     */
    void addAsks(SupervisorHolon newAsks);

    /**
     * Removes a Asks property value.<p>
     * 
     * @param oldAsks the Asks property value to be removed.
     */
    void removeAsks(SupervisorHolon oldAsks);


    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#STHAnswerPH
     */
     
    /**
     * Gets all property values for the STHAnswerPH property.<p>
     * 
     * @returns a collection of values for the STHAnswerPH property.
     */
    Collection<? extends ProductHolon> getSTHAnswerPH();

    /**
     * Checks if the class has a STHAnswerPH property value.<p>
     * 
     * @return true if there is a STHAnswerPH property value.
     */
    boolean hasSTHAnswerPH();

    /**
     * Adds a STHAnswerPH property value.<p>
     * 
     * @param newSTHAnswerPH the STHAnswerPH property value to be added
     */
    void addSTHAnswerPH(ProductHolon newSTHAnswerPH);

    /**
     * Removes a STHAnswerPH property value.<p>
     * 
     * @param oldSTHAnswerPH the STHAnswerPH property value to be removed.
     */
    void removeSTHAnswerPH(ProductHolon oldSTHAnswerPH);


    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#HardwareNeeded
     */
     
    /**
     * Gets all property values for the HardwareNeeded property.<p>
     * 
     * @returns a collection of values for the HardwareNeeded property.
     */
    Collection<? extends String> getHardwareNeeded();

    /**
     * Checks if the class has a HardwareNeeded property value.<p>
     * 
     * @return true if there is a HardwareNeeded property value.
     */
    boolean hasHardwareNeeded();

    /**
     * Adds a HardwareNeeded property value.<p>
     * 
     * @param newHardwareNeeded the HardwareNeeded property value to be added
     */
    void addHardwareNeeded(String newHardwareNeeded);

    /**
     * Removes a HardwareNeeded property value.<p>
     * 
     * @param oldHardwareNeeded the HardwareNeeded property value to be removed.
     */
    void removeHardwareNeeded(String oldHardwareNeeded);



    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ID
     */
     
    /**
     * Gets all property values for the ID property.<p>
     * 
     * @returns a collection of values for the ID property.
     */
    Collection<? extends String> getID();

    /**
     * Checks if the class has a ID property value.<p>
     * 
     * @return true if there is a ID property value.
     */
    boolean hasID();

    /**
     * Adds a ID property value.<p>
     * 
     * @param newID the ID property value to be added
     */
    void addID(String newID);

    /**
     * Removes a ID property value.<p>
     * 
     * @param oldID the ID property value to be removed.
     */
    void removeID(String oldID);



    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Name
     */
     
    /**
     * Gets all property values for the Name property.<p>
     * 
     * @returns a collection of values for the Name property.
     */
    Collection<? extends String> getName();

    /**
     * Checks if the class has a Name property value.<p>
     * 
     * @return true if there is a Name property value.
     */
    boolean hasName();

    /**
     * Adds a Name property value.<p>
     * 
     * @param newName the Name property value to be added
     */
    void addName(String newName);

    /**
     * Removes a Name property value.<p>
     * 
     * @param oldName the Name property value to be removed.
     */
    void removeName(String oldName);



    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Supervisors
     */
     
    /**
     * Gets all property values for the Supervisors property.<p>
     * 
     * @returns a collection of values for the Supervisors property.
     */
    Collection<? extends String> getSupervisors();

    /**
     * Checks if the class has a Supervisors property value.<p>
     * 
     * @return true if there is a Supervisors property value.
     */
    boolean hasSupervisors();

    /**
     * Adds a Supervisors property value.<p>
     * 
     * @param newSupervisors the Supervisors property value to be added
     */
    void addSupervisors(String newSupervisors);

    /**
     * Removes a Supervisors property value.<p>
     * 
     * @param oldSupervisors the Supervisors property value to be removed.
     */
    void removeSupervisors(String oldSupervisors);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
