package 3oTrabProtege;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: SupervisorHolon <br>
 * @version generated on Wed Dec 28 18:45:57 GMT 2016 by dmrg
 */

public interface SupervisorHolon extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#AnswerSTH
     */
     
    /**
     * Gets all property values for the AnswerSTH property.<p>
     * 
     * @returns a collection of values for the AnswerSTH property.
     */
    Collection<? extends SimpleTaskHolon> getAnswerSTH();

    /**
     * Checks if the class has a AnswerSTH property value.<p>
     * 
     * @return true if there is a AnswerSTH property value.
     */
    boolean hasAnswerSTH();

    /**
     * Adds a AnswerSTH property value.<p>
     * 
     * @param newAnswerSTH the AnswerSTH property value to be added
     */
    void addAnswerSTH(SimpleTaskHolon newAnswerSTH);

    /**
     * Removes a AnswerSTH property value.<p>
     * 
     * @param oldAnswerSTH the AnswerSTH property value to be removed.
     */
    void removeAnswerSTH(SimpleTaskHolon oldAnswerSTH);


    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Executes
     */
     
    /**
     * Gets all property values for the Executes property.<p>
     * 
     * @returns a collection of values for the Executes property.
     */
    Collection<? extends OperationalHolon> getExecutes();

    /**
     * Checks if the class has a Executes property value.<p>
     * 
     * @return true if there is a Executes property value.
     */
    boolean hasExecutes();

    /**
     * Adds a Executes property value.<p>
     * 
     * @param newExecutes the Executes property value to be added
     */
    void addExecutes(OperationalHolon newExecutes);

    /**
     * Removes a Executes property value.<p>
     * 
     * @param oldExecutes the Executes property value to be removed.
     */
    void removeExecutes(OperationalHolon oldExecutes);


    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ID
     */
     
    /**
     * Gets all property values for the ID property.<p>
     * 
     * @returns a collection of values for the ID property.
     */
    Collection<? extends String> getID();

    /**
     * Checks if the class has a ID property value.<p>
     * 
     * @return true if there is a ID property value.
     */
    boolean hasID();

    /**
     * Adds a ID property value.<p>
     * 
     * @param newID the ID property value to be added
     */
    void addID(String newID);

    /**
     * Removes a ID property value.<p>
     * 
     * @param oldID the ID property value to be removed.
     */
    void removeID(String oldID);



    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Name
     */
     
    /**
     * Gets all property values for the Name property.<p>
     * 
     * @returns a collection of values for the Name property.
     */
    Collection<? extends String> getName();

    /**
     * Checks if the class has a Name property value.<p>
     * 
     * @return true if there is a Name property value.
     */
    boolean hasName();

    /**
     * Adds a Name property value.<p>
     * 
     * @param newName the Name property value to be added
     */
    void addName(String newName);

    /**
     * Removes a Name property value.<p>
     * 
     * @param oldName the Name property value to be removed.
     */
    void removeName(String oldName);



    /* ***************************************************
     * Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Operationals
     */
     
    /**
     * Gets all property values for the Operationals property.<p>
     * 
     * @returns a collection of values for the Operationals property.
     */
    Collection<? extends String> getOperationals();

    /**
     * Checks if the class has a Operationals property value.<p>
     * 
     * @return true if there is a Operationals property value.
     */
    boolean hasOperationals();

    /**
     * Adds a Operationals property value.<p>
     * 
     * @param newOperationals the Operationals property value to be added
     */
    void addOperationals(String newOperationals);

    /**
     * Removes a Operationals property value.<p>
     * 
     * @param oldOperationals the Operationals property value to be removed.
     */
    void removeOperationals(String oldOperationals);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
