package 3oTrabProtege;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Wed Dec 28 18:45:57 GMT 2016 by dmrg
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ComplexTaskHolon
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPLEXTASKHOLON.<p>
     * 
     */
    public static final OWLClass CLASS_COMPLEXTASKHOLON = factory.getOWLClass(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ComplexTaskHolon"));

    /* ***************************************************
     * Class http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#OperationalHolon
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OPERATIONALHOLON.<p>
     * 
     */
    public static final OWLClass CLASS_OPERATIONALHOLON = factory.getOWLClass(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#OperationalHolon"));

    /* ***************************************************
     * Class http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ProductHolon
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRODUCTHOLON.<p>
     * 
     */
    public static final OWLClass CLASS_PRODUCTHOLON = factory.getOWLClass(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ProductHolon"));

    /* ***************************************************
     * Class http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#SimpleTaskHolon
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SIMPLETASKHOLON.<p>
     * 
     */
    public static final OWLClass CLASS_SIMPLETASKHOLON = factory.getOWLClass(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#SimpleTaskHolon"));

    /* ***************************************************
     * Class http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#SupervisorHolon
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SUPERVISORHOLON.<p>
     * 
     */
    public static final OWLClass CLASS_SUPERVISORHOLON = factory.getOWLClass(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#SupervisorHolon"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Answer
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ANSWER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ANSWER = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Answer"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#AnswerCTH
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ANSWERCTH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ANSWERCTH = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#AnswerCTH"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#AnswerSTH
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ANSWERSTH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ANSWERSTH = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#AnswerSTH"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Asks
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ASKS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ASKS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Asks"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#AsksSimple
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ASKSSIMPLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ASKSSIMPLE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#AsksSimple"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#CTHAnswerPH
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CTHANSWERPH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CTHANSWERPH = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#CTHAnswerPH"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ContainsComplex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINSCOMPLEX.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINSCOMPLEX = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ContainsComplex"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ContainsSimple
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINSSIMPLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINSSIMPLE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ContainsSimple"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Executes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXECUTES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXECUTES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Executes"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#STHAnswerPH
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property STHANSWERPH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_STHANSWERPH = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#STHAnswerPH"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#HardwareNeeded
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HARDWARENEEDED.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HARDWARENEEDED = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#HardwareNeeded"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#HardwareType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HARDWARETYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HARDWARETYPE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#HardwareType"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#ID"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Location
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LOCATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LOCATION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Location"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Name"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Operationals
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OPERATIONALS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OPERATIONALS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Operationals"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Priority
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PRIORITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PRIORITY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Priority"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#SubTasks
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SUBTASKS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SUBTASKS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#SubTasks"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Supervisors
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SUPERVISORS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SUPERVISORS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Supervisors"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Tasks
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TASKS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TASKS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/dmrgo/ontologies/2016/9/finalOntology#Tasks"));


}
