/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Simulation;

import Transport.Conveyor;
import Transport.Diverter;
import Transport.Item;
import java.util.HashMap;
import java.util.LinkedList;

/**
 *
 * @author André Dionisio Rocha
 */
public class Layout1 extends javax.swing.JFrame {

    /**
     * Creates new form Layout1
     */
    LinkedList<Integer> produced = new LinkedList<>();

    public Layout1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel21 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        D_8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        C_10_2 = new javax.swing.JLabel();
        C_10_1 = new javax.swing.JLabel();
        C_10_0 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        Si = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        C_9_0 = new javax.swing.JLabel();
        C_9_1 = new javax.swing.JLabel();
        C_9_2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        C_3_2 = new javax.swing.JLabel();
        C_3_1 = new javax.swing.JLabel();
        C_3_0 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        C_6_4 = new javax.swing.JLabel();
        C_6_3 = new javax.swing.JLabel();
        C_6_2 = new javax.swing.JLabel();
        C_6_1 = new javax.swing.JLabel();
        C_6_0 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        C_5_4 = new javax.swing.JLabel();
        C_5_3 = new javax.swing.JLabel();
        C_5_2 = new javax.swing.JLabel();
        C_5_1 = new javax.swing.JLabel();
        C_5_0 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        D_3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        C_2_0 = new javax.swing.JLabel();
        C_2_1 = new javax.swing.JLabel();
        C_2_2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        C_1_2 = new javax.swing.JLabel();
        C_1_1 = new javax.swing.JLabel();
        C_1_0 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        C_4_4 = new javax.swing.JLabel();
        C_4_3 = new javax.swing.JLabel();
        C_4_2 = new javax.swing.JLabel();
        C_4_1 = new javax.swing.JLabel();
        C_4_0 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        C_7_4 = new javax.swing.JLabel();
        C_7_3 = new javax.swing.JLabel();
        C_7_2 = new javax.swing.JLabel();
        C_7_1 = new javax.swing.JLabel();
        C_7_0 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        So = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        D_2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        D_4 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        D_7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        C_8_2 = new javax.swing.JLabel();
        C_8_1 = new javax.swing.JLabel();
        C_8_0 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        D_6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        D_1 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        D_5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEntries = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaExits = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMeanTime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel20.setBackground(new java.awt.Color(153, 153, 153));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        D_8.setBackground(new java.awt.Color(153, 153, 153));
        D_8.setForeground(new java.awt.Color(153, 153, 153));
        D_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        D_8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        D_8.setEnabled(false);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        C_10_2.setBackground(new java.awt.Color(153, 153, 153));
        C_10_2.setForeground(new java.awt.Color(153, 153, 153));
        C_10_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_10_2.setEnabled(false);

        C_10_1.setBackground(new java.awt.Color(153, 153, 153));
        C_10_1.setForeground(new java.awt.Color(153, 153, 153));
        C_10_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_10_1.setEnabled(false);

        C_10_0.setBackground(new java.awt.Color(153, 153, 153));
        C_10_0.setForeground(new java.awt.Color(153, 153, 153));
        C_10_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_10_0.setEnabled(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(C_10_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_10_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_10_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(C_10_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_10_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_10_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(153, 153, 153));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Si.setBackground(new java.awt.Color(153, 153, 153));
        Si.setForeground(new java.awt.Color(153, 153, 153));
        Si.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        Si.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Si.setEnabled(false);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Si, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Si, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel15.setBackground(new java.awt.Color(153, 153, 153));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        C_9_0.setBackground(new java.awt.Color(153, 153, 153));
        C_9_0.setForeground(new java.awt.Color(153, 153, 153));
        C_9_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_9_0.setEnabled(false);

        C_9_1.setBackground(new java.awt.Color(153, 153, 153));
        C_9_1.setForeground(new java.awt.Color(153, 153, 153));
        C_9_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_9_1.setEnabled(false);

        C_9_2.setBackground(new java.awt.Color(153, 153, 153));
        C_9_2.setForeground(new java.awt.Color(153, 153, 153));
        C_9_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_9_2.setEnabled(false);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C_9_0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_9_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_9_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(C_9_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_9_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_9_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        C_3_2.setBackground(new java.awt.Color(153, 153, 153));
        C_3_2.setForeground(new java.awt.Color(153, 153, 153));
        C_3_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_3_2.setEnabled(false);

        C_3_1.setBackground(new java.awt.Color(153, 153, 153));
        C_3_1.setForeground(new java.awt.Color(153, 153, 153));
        C_3_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_3_1.setEnabled(false);

        C_3_0.setBackground(new java.awt.Color(153, 153, 153));
        C_3_0.setForeground(new java.awt.Color(153, 153, 153));
        C_3_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_3_0.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C_3_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_3_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_3_0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(C_3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_3_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        C_6_4.setBackground(new java.awt.Color(153, 153, 153));
        C_6_4.setForeground(new java.awt.Color(153, 153, 153));
        C_6_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_6_4.setEnabled(false);

        C_6_3.setBackground(new java.awt.Color(153, 153, 153));
        C_6_3.setForeground(new java.awt.Color(153, 153, 153));
        C_6_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_6_3.setEnabled(false);

        C_6_2.setBackground(new java.awt.Color(153, 153, 153));
        C_6_2.setForeground(new java.awt.Color(153, 153, 153));
        C_6_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_6_2.setEnabled(false);

        C_6_1.setBackground(new java.awt.Color(153, 153, 153));
        C_6_1.setForeground(new java.awt.Color(153, 153, 153));
        C_6_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_6_1.setEnabled(false);

        C_6_0.setBackground(new java.awt.Color(153, 153, 153));
        C_6_0.setForeground(new java.awt.Color(153, 153, 153));
        C_6_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_6_0.setEnabled(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(C_6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_6_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(C_6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(C_6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(C_6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(C_6_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(C_6_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        C_5_4.setBackground(new java.awt.Color(153, 153, 153));
        C_5_4.setForeground(new java.awt.Color(153, 153, 153));
        C_5_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_5_4.setEnabled(false);

        C_5_3.setBackground(new java.awt.Color(153, 153, 153));
        C_5_3.setForeground(new java.awt.Color(153, 153, 153));
        C_5_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_5_3.setEnabled(false);

        C_5_2.setBackground(new java.awt.Color(153, 153, 153));
        C_5_2.setForeground(new java.awt.Color(153, 153, 153));
        C_5_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_5_2.setEnabled(false);

        C_5_1.setBackground(new java.awt.Color(153, 153, 153));
        C_5_1.setForeground(new java.awt.Color(153, 153, 153));
        C_5_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_5_1.setEnabled(false);

        C_5_0.setBackground(new java.awt.Color(153, 153, 153));
        C_5_0.setForeground(new java.awt.Color(153, 153, 153));
        C_5_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_5_0.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(C_5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_5_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C_5_4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_5_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_5_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_5_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_5_0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        D_3.setBackground(new java.awt.Color(153, 153, 153));
        D_3.setForeground(new java.awt.Color(153, 153, 153));
        D_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        D_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        D_3.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        C_2_0.setBackground(new java.awt.Color(153, 153, 153));
        C_2_0.setForeground(new java.awt.Color(153, 153, 153));
        C_2_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_2_0.setEnabled(false);

        C_2_1.setBackground(new java.awt.Color(153, 153, 153));
        C_2_1.setForeground(new java.awt.Color(153, 153, 153));
        C_2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_2_1.setEnabled(false);

        C_2_2.setBackground(new java.awt.Color(153, 153, 153));
        C_2_2.setForeground(new java.awt.Color(153, 153, 153));
        C_2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_2_2.setEnabled(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C_2_0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_2_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_2_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(C_2_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        C_1_2.setBackground(new java.awt.Color(153, 153, 153));
        C_1_2.setForeground(new java.awt.Color(153, 153, 153));
        C_1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_1_2.setEnabled(false);

        C_1_1.setBackground(new java.awt.Color(153, 153, 153));
        C_1_1.setForeground(new java.awt.Color(153, 153, 153));
        C_1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_1_1.setEnabled(false);

        C_1_0.setBackground(new java.awt.Color(153, 153, 153));
        C_1_0.setForeground(new java.awt.Color(153, 153, 153));
        C_1_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_1_0.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(C_1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(C_1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(C_1_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(C_1_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        C_4_4.setBackground(new java.awt.Color(153, 153, 153));
        C_4_4.setForeground(new java.awt.Color(153, 153, 153));
        C_4_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_4_4.setEnabled(false);

        C_4_3.setBackground(new java.awt.Color(153, 153, 153));
        C_4_3.setForeground(new java.awt.Color(153, 153, 153));
        C_4_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_4_3.setEnabled(false);

        C_4_2.setBackground(new java.awt.Color(153, 153, 153));
        C_4_2.setForeground(new java.awt.Color(153, 153, 153));
        C_4_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_4_2.setEnabled(false);

        C_4_1.setBackground(new java.awt.Color(153, 153, 153));
        C_4_1.setForeground(new java.awt.Color(153, 153, 153));
        C_4_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_4_1.setEnabled(false);

        C_4_0.setBackground(new java.awt.Color(153, 153, 153));
        C_4_0.setForeground(new java.awt.Color(153, 153, 153));
        C_4_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_4_0.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(C_4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_4_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(C_4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_4_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_4_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        C_7_4.setBackground(new java.awt.Color(153, 153, 153));
        C_7_4.setForeground(new java.awt.Color(153, 153, 153));
        C_7_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_7_4.setEnabled(false);

        C_7_3.setBackground(new java.awt.Color(153, 153, 153));
        C_7_3.setForeground(new java.awt.Color(153, 153, 153));
        C_7_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_7_3.setEnabled(false);

        C_7_2.setBackground(new java.awt.Color(153, 153, 153));
        C_7_2.setForeground(new java.awt.Color(153, 153, 153));
        C_7_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_7_2.setEnabled(false);

        C_7_1.setBackground(new java.awt.Color(153, 153, 153));
        C_7_1.setForeground(new java.awt.Color(153, 153, 153));
        C_7_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_7_1.setEnabled(false);

        C_7_0.setBackground(new java.awt.Color(153, 153, 153));
        C_7_0.setForeground(new java.awt.Color(153, 153, 153));
        C_7_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_7_0.setEnabled(false);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(C_7_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_7_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(C_7_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(C_7_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(C_7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(C_7_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(C_7_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        So.setBackground(new java.awt.Color(153, 153, 153));
        So.setForeground(new java.awt.Color(153, 153, 153));
        So.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        So.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        So.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(So, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(So, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel9.setBackground(new java.awt.Color(0, 0, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        D_2.setBackground(new java.awt.Color(0, 51, 255));
        D_2.setForeground(new java.awt.Color(0, 0, 255));
        D_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        D_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        D_2.setEnabled(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        D_4.setBackground(new java.awt.Color(153, 153, 153));
        D_4.setForeground(new java.awt.Color(153, 153, 153));
        D_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/StationIcon.png"))); // NOI18N
        D_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        D_4.setEnabled(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel18.setBackground(new java.awt.Color(153, 153, 153));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        D_7.setBackground(new java.awt.Color(153, 153, 153));
        D_7.setForeground(new java.awt.Color(153, 153, 153));
        D_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        D_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        D_7.setEnabled(false);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Layout 1");

        jPanel14.setBackground(new java.awt.Color(153, 153, 153));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        C_8_2.setBackground(new java.awt.Color(153, 153, 153));
        C_8_2.setForeground(new java.awt.Color(153, 153, 153));
        C_8_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_8_2.setEnabled(false);

        C_8_1.setBackground(new java.awt.Color(153, 153, 153));
        C_8_1.setForeground(new java.awt.Color(153, 153, 153));
        C_8_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_8_1.setEnabled(false);

        C_8_0.setBackground(new java.awt.Color(153, 153, 153));
        C_8_0.setForeground(new java.awt.Color(153, 153, 153));
        C_8_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        C_8_0.setEnabled(false);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C_8_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_8_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_8_0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(C_8_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_8_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_8_0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Arrow.png"))); // NOI18N

        jPanel17.setBackground(new java.awt.Color(153, 153, 153));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        D_6.setBackground(new java.awt.Color(153, 153, 153));
        D_6.setForeground(new java.awt.Color(153, 153, 153));
        D_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        D_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        D_6.setEnabled(false);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Arrow.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        D_1.setBackground(new java.awt.Color(153, 153, 153));
        D_1.setForeground(new java.awt.Color(153, 153, 153));
        D_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ProductIcon.png"))); // NOI18N
        D_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        D_1.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel16.setBackground(new java.awt.Color(153, 153, 153));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        D_5.setBackground(new java.awt.Color(153, 153, 153));
        D_5.setForeground(new java.awt.Color(153, 153, 153));
        D_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/StationIcon.png"))); // NOI18N
        D_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        D_5.setEnabled(false);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(D_5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("D_4");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("D_5");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel21Layout.createSequentialGroup()
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel21Layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel21Layout.createSequentialGroup()
                                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel21Layout.createSequentialGroup()
                                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jTextAreaEntries.setColumns(20);
        jTextAreaEntries.setRows(5);
        jScrollPane1.setViewportView(jTextAreaEntries);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Entries");

        jTextAreaExits.setColumns(20);
        jTextAreaExits.setRows(5);
        jScrollPane2.setViewportView(jTextAreaExits);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Exits");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Mean Time to Produce (seconds)");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jTextFieldMeanTime, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5))
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMeanTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 984, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Layout1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Layout1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Layout1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Layout1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Layout1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel C_10_0;
    private javax.swing.JLabel C_10_1;
    private javax.swing.JLabel C_10_2;
    private javax.swing.JLabel C_1_0;
    private javax.swing.JLabel C_1_1;
    private javax.swing.JLabel C_1_2;
    private javax.swing.JLabel C_2_0;
    private javax.swing.JLabel C_2_1;
    private javax.swing.JLabel C_2_2;
    private javax.swing.JLabel C_3_0;
    private javax.swing.JLabel C_3_1;
    private javax.swing.JLabel C_3_2;
    private javax.swing.JLabel C_4_0;
    private javax.swing.JLabel C_4_1;
    private javax.swing.JLabel C_4_2;
    private javax.swing.JLabel C_4_3;
    private javax.swing.JLabel C_4_4;
    private javax.swing.JLabel C_5_0;
    private javax.swing.JLabel C_5_1;
    private javax.swing.JLabel C_5_2;
    private javax.swing.JLabel C_5_3;
    private javax.swing.JLabel C_5_4;
    private javax.swing.JLabel C_6_0;
    private javax.swing.JLabel C_6_1;
    private javax.swing.JLabel C_6_2;
    private javax.swing.JLabel C_6_3;
    private javax.swing.JLabel C_6_4;
    private javax.swing.JLabel C_7_0;
    private javax.swing.JLabel C_7_1;
    private javax.swing.JLabel C_7_2;
    private javax.swing.JLabel C_7_3;
    private javax.swing.JLabel C_7_4;
    private javax.swing.JLabel C_8_0;
    private javax.swing.JLabel C_8_1;
    private javax.swing.JLabel C_8_2;
    private javax.swing.JLabel C_9_0;
    private javax.swing.JLabel C_9_1;
    private javax.swing.JLabel C_9_2;
    private javax.swing.JLabel D_1;
    private javax.swing.JLabel D_2;
    private javax.swing.JLabel D_3;
    private javax.swing.JLabel D_4;
    private javax.swing.JLabel D_5;
    private javax.swing.JLabel D_6;
    private javax.swing.JLabel D_7;
    private javax.swing.JLabel D_8;
    private javax.swing.JLabel Si;
    private javax.swing.JLabel So;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaEntries;
    private javax.swing.JTextArea jTextAreaExits;
    private javax.swing.JTextField jTextFieldMeanTime;
    // End of variables declaration//GEN-END:variables

    public void updateState(HashMap<String, Diverter> myDiverters, HashMap<String, Conveyor> myConveyors) {
        cleanLayout();
        updateDiverters(myDiverters);
        updateConveyors(myConveyors);
    }

    private void cleanLayout() {
        //Clean Source
        So.setEnabled(false);

        //Clean Sink
        Si.setEnabled(false);

        //Clean Diverters
        D_1.setEnabled(false);
        D_2.setEnabled(false);
        D_3.setEnabled(false);
        D_4.setEnabled(false);
        D_5.setEnabled(false);
        D_6.setEnabled(false);
        D_7.setEnabled(false);
        D_8.setEnabled(false);

        //Clean Conveyors
        //C_1
        C_1_0.setEnabled(false);
        C_1_1.setEnabled(false);
        C_1_2.setEnabled(false);

        //C_2
        C_2_0.setEnabled(false);
        C_2_1.setEnabled(false);
        C_2_2.setEnabled(false);

        //C_3
        C_3_0.setEnabled(false);
        C_3_1.setEnabled(false);
        C_3_2.setEnabled(false);

        //C_4
        C_4_0.setEnabled(false);
        C_4_1.setEnabled(false);
        C_4_2.setEnabled(false);
        C_4_3.setEnabled(false);
        C_4_4.setEnabled(false);

        //C_5
        C_5_0.setEnabled(false);
        C_5_1.setEnabled(false);
        C_5_2.setEnabled(false);
        C_5_3.setEnabled(false);
        C_5_4.setEnabled(false);

        //C_6
        C_6_0.setEnabled(false);
        C_6_1.setEnabled(false);
        C_6_2.setEnabled(false);
        C_6_3.setEnabled(false);
        C_6_4.setEnabled(false);

        //C_7
        C_7_0.setEnabled(false);
        C_7_1.setEnabled(false);
        C_7_2.setEnabled(false);
        C_7_3.setEnabled(false);
        C_7_4.setEnabled(false);

        //C_8
        C_8_0.setEnabled(false);
        C_8_1.setEnabled(false);
        C_8_2.setEnabled(false);

        //C_9
        C_9_0.setEnabled(false);
        C_9_1.setEnabled(false);
        C_9_2.setEnabled(false);

        //C_10
        C_10_0.setEnabled(false);
        C_10_1.setEnabled(false);
        C_10_2.setEnabled(false);

    }

    private void updateDiverters(HashMap<String, Diverter> myDiverters) {
        for (Diverter div : myDiverters.values()) {
            if (div.getMyItem() != null) {
                switch (div.getID()) {
                    case ("So"):
                        this.So.setEnabled(true);
                        break;
                    case ("Si"):
                        this.Si.setEnabled(true);
                        break;
                    case ("D_1"):
                        this.D_1.setEnabled(true);
                        break;
                    case ("D_2"):
                        this.D_2.setEnabled(true);
                        break;
                    case ("D_3"):
                        this.D_3.setEnabled(true);
                        break;
                    case ("D_4"):
                        this.D_4.setEnabled(true);
                        break;
                    case ("D_5"):
                        this.D_5.setEnabled(true);
                        break;
                    case ("D_6"):
                        this.D_6.setEnabled(true);
                        break;
                    case ("D_7"):
                        this.D_7.setEnabled(true);
                        break;
                    case ("D_8"):
                        this.D_8.setEnabled(true);
                        break;
                }
            }
        }
    }

    private void updateConveyors(HashMap<String, Conveyor> myConveyors) {
        for (Conveyor conv : myConveyors.values()) {
            LinkedList<Item> inventory = conv.getInventory();
            for (Item item : inventory) {
                switch (conv.getID()) {
                    case ("C_1"):
                        switch (item.getPosition()) {
                            case (0):
                                this.C_1_0.setEnabled(true);
                                break;
                            case (1):
                                this.C_1_1.setEnabled(true);
                                break;
                            case (2):
                                this.C_1_2.setEnabled(true);
                                break;
                        }
                        break;
                    case ("C_2"):
                        switch (item.getPosition()) {
                            case (0):
                                this.C_2_0.setEnabled(true);
                                break;
                            case (1):
                                this.C_2_1.setEnabled(true);
                                break;
                            case (2):
                                this.C_2_2.setEnabled(true);
                                break;
                        }
                        break;
                    case ("C_3"):
                        switch (item.getPosition()) {
                            case (0):
                                this.C_3_0.setEnabled(true);
                                break;
                            case (1):
                                this.C_3_1.setEnabled(true);
                                break;
                            case (2):
                                this.C_3_2.setEnabled(true);
                                break;
                        }
                        break;
                    case ("C_4"):
                        switch (item.getPosition()) {
                            case (0):
                                this.C_4_0.setEnabled(true);
                                break;
                            case (1):
                                this.C_4_1.setEnabled(true);
                                break;
                            case (2):
                                this.C_4_2.setEnabled(true);
                                break;
                            case (3):
                                this.C_4_3.setEnabled(true);
                                break;
                            case (4):
                                this.C_4_4.setEnabled(true);
                                break;
                        }
                        break;
                    case ("C_5"):
                        switch (item.getPosition()) {
                            case (0):
                                this.C_5_0.setEnabled(true);
                                break;
                            case (1):
                                this.C_5_1.setEnabled(true);
                                break;
                            case (2):
                                this.C_5_2.setEnabled(true);
                                break;
                            case (3):
                                this.C_5_3.setEnabled(true);
                                break;
                            case (4):
                                this.C_5_4.setEnabled(true);
                                break;
                        }
                        break;
                    case ("C_6"):
                        switch (item.getPosition()) {
                            case (0):
                                this.C_6_0.setEnabled(true);
                                break;
                            case (1):
                                this.C_6_1.setEnabled(true);
                                break;
                            case (2):
                                this.C_6_2.setEnabled(true);
                                break;
                            case (3):
                                this.C_6_3.setEnabled(true);
                                break;
                            case (4):
                                this.C_6_4.setEnabled(true);
                                break;
                        }
                        break;
                    case ("C_7"):
                        switch (item.getPosition()) {
                            case (0):
                                this.C_7_0.setEnabled(true);
                                break;
                            case (1):
                                this.C_7_1.setEnabled(true);
                                break;
                            case (2):
                                this.C_7_2.setEnabled(true);
                                break;
                            case (3):
                                this.C_7_3.setEnabled(true);
                                break;
                            case (4):
                                this.C_7_4.setEnabled(true);
                                break;
                        }
                        break;
                    case ("C_8"):
                        switch (item.getPosition()) {
                            case (0):
                                this.C_8_0.setEnabled(true);
                                break;
                            case (1):
                                this.C_8_1.setEnabled(true);
                                break;
                            case (2):
                                this.C_8_2.setEnabled(true);
                                break;
                        }
                        break;
                    case ("C_9"):
                        switch (item.getPosition()) {
                            case (0):
                                this.C_9_0.setEnabled(true);
                                break;
                            case (1):
                                this.C_9_1.setEnabled(true);
                                break;
                            case (2):
                                this.C_9_2.setEnabled(true);
                                break;
                        }
                        break;
                    case ("C_10"):
                        switch (item.getPosition()) {
                            case (0):
                                this.C_10_0.setEnabled(true);
                                break;
                            case (1):
                                this.C_10_1.setEnabled(true);
                                break;
                            case (2):
                                this.C_10_2.setEnabled(true);
                                break;
                        }
                        break;
                }
            }
        }
    }

    public void finishProduct(Item myItem) {
        int timeToProduce = (int) ((System.currentTimeMillis() - myItem.getEntryDate()) / 1000);
        produced.add(timeToProduce);
        int mean = 0;
        for (Integer next : produced) {
            mean += next;
        }
        mean = mean / produced.size();
        this.jTextFieldMeanTime.setText("" + mean);
        this.jTextAreaExits.append(myItem.getID() + "\t Time to Produce (seconds): " + timeToProduce);
        this.jTextAreaExits.append("\n");
    }

    public void launchProduct(Item newItem) {
        this.jTextAreaEntries.append(newItem.getID());
        this.jTextAreaEntries.append("\n");
    }
}
