package com.issiaa2016.semanticmodelimpl;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Product <br>
 * @version generated on Sun Oct 16 15:26:31 BST 2016 by dmrgo
 */

public interface Product extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#consumes
     */
     
    /**
     * Gets all property values for the consumes property.<p>
     * 
     * @returns a collection of values for the consumes property.
     */
    Collection<? extends Skill> getConsumes();

    /**
     * Checks if the class has a consumes property value.<p>
     * 
     * @return true if there is a consumes property value.
     */
    boolean hasConsumes();

    /**
     * Adds a consumes property value.<p>
     * 
     * @param newConsumes the consumes property value to be added
     */
    void addConsumes(Skill newConsumes);

    /**
     * Removes a consumes property value.<p>
     * 
     * @param oldConsumes the consumes property value to be removed.
     */
    void removeConsumes(Skill oldConsumes);


    /* ***************************************************
     * Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Description
     */
     
    /**
     * Gets all property values for the Description property.<p>
     * 
     * @returns a collection of values for the Description property.
     */
    Collection<? extends String> getDescription();

    /**
     * Checks if the class has a Description property value.<p>
     * 
     * @return true if there is a Description property value.
     */
    boolean hasDescription();

    /**
     * Adds a Description property value.<p>
     * 
     * @param newDescription the Description property value to be added
     */
    void addDescription(String newDescription);

    /**
     * Removes a Description property value.<p>
     * 
     * @param oldDescription the Description property value to be removed.
     */
    void removeDescription(String oldDescription);



    /* ***************************************************
     * Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Friendly_Name
     */
     
    /**
     * Gets all property values for the Friendly_Name property.<p>
     * 
     * @returns a collection of values for the Friendly_Name property.
     */
    Collection<? extends String> getFriendly_Name();

    /**
     * Checks if the class has a Friendly_Name property value.<p>
     * 
     * @return true if there is a Friendly_Name property value.
     */
    boolean hasFriendly_Name();

    /**
     * Adds a Friendly_Name property value.<p>
     * 
     * @param newFriendly_Name the Friendly_Name property value to be added
     */
    void addFriendly_Name(String newFriendly_Name);

    /**
     * Removes a Friendly_Name property value.<p>
     * 
     * @param oldFriendly_Name the Friendly_Name property value to be removed.
     */
    void removeFriendly_Name(String oldFriendly_Name);



    /* ***************************************************
     * Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#ID
     */
     
    /**
     * Gets all property values for the ID property.<p>
     * 
     * @returns a collection of values for the ID property.
     */
    Collection<? extends String> getID();

    /**
     * Checks if the class has a ID property value.<p>
     * 
     * @return true if there is a ID property value.
     */
    boolean hasID();

    /**
     * Adds a ID property value.<p>
     * 
     * @param newID the ID property value to be added
     */
    void addID(String newID);

    /**
     * Removes a ID property value.<p>
     * 
     * @param oldID the ID property value to be removed.
     */
    void removeID(String oldID);



    /* ***************************************************
     * Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Skills
     */
     
    /**
     * Gets all property values for the Skills property.<p>
     * 
     * @returns a collection of values for the Skills property.
     */
    Collection<? extends Object> getSkills();

    /**
     * Checks if the class has a Skills property value.<p>
     * 
     * @return true if there is a Skills property value.
     */
    boolean hasSkills();

    /**
     * Adds a Skills property value.<p>
     * 
     * @param newSkills the Skills property value to be added
     */
    void addSkills(Object newSkills);

    /**
     * Removes a Skills property value.<p>
     * 
     * @param oldSkills the Skills property value to be removed.
     */
    void removeSkills(Object oldSkills);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
