package com.issiaa2016.semanticmodelimpl;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sun Oct 16 15:26:31 BST 2016 by dmrgo
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Parameter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARAMETER.<p>
     * 
     */
    public static final OWLClass CLASS_PARAMETER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Parameter"));

    /* ***************************************************
     * Class http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Product
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRODUCT.<p>
     * 
     */
    public static final OWLClass CLASS_PRODUCT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Product"));

    /* ***************************************************
     * Class http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Resource
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESOURCE.<p>
     * 
     */
    public static final OWLClass CLASS_RESOURCE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Resource"));

    /* ***************************************************
     * Class http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Skill
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SKILL.<p>
     * 
     */
    public static final OWLClass CLASS_SKILL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Skill"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#consumes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONSUMES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONSUMES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#consumes"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#contains
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#contains"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#executes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXECUTES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXECUTES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#executes"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Description
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DESCRIPTION = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Description"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Friendly_Name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FRIENDLY_NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FRIENDLY_NAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Friendly_Name"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#ID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ID = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#ID"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Manufacturer
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MANUFACTURER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MANUFACTURER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Manufacturer"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Parameters
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property PARAMETERS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_PARAMETERS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Parameters"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Skills
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property SKILLS.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_SKILLS = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Skills"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Type
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TYPE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Type"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Value
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VALUE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/issiaa2016/ontologies/myOntology#Value"));


}
